### ISSUE TITLE
Number IDs issue

### ISSUE THREAD

**Issue by taorkon** [lehkost/RusDraCor#5]
in Chehov_Ivanov 1-й гость, 2-й гость и 3-й гость had the same id "#PerviyGost"

**Comment by lehkost** [comment]
yes, we had this case before. unfortunately, IDs can't start with numbers, so allowing numbers in IDs would result in "1jGost" and is no solution. we should change  1-й, 2-й, 3-й, etc. in speaker names to their equivalent ordinal numerals in full, like "Perviy", "Vtoroj", etc.
