### ISSUE TITLE
WRONG PERSON LIST

### ISSUE THREAD

**Issue by taorkon** [lehkost/RusDraCor#7]
in the Plavilschikov Sgovor Kutejkina the person list is the same as cost list

**Comment by lehkost** [comment]
yes, the reason is that we were already working on it before matvey fixed the particDesc problem. @matveykolbasov, could you maybe generate the particDesc list for this play separately and then insert it manually into the file? thanks in advance!

**Comment by lehkost** [comment]
Two duplicate IDs were removed, should be okay now.
