### ISSUE TITLE
Soft Sounds

### ISSUE THREAD

**Issue by taorkon** [lehkost/RusDraCor#8]
Should we mark soft sounds? Previously there was no ' in transliteration

Here it is
**Turgenev Neostorozhnost'
Gogol' Teatral'nyj_raz'ezd_posle_predstavlenija_novoj_komedii
Chehov Tat'jana_Repina**

And that is how older files look like
**Blok Korol_na_ploschadi
Pushkin Kamennyj_gost
Pushkin Skupoj_rytsar**

**Comment by lehkost** [comment]
Problem solved with recent reorganisation of repo.
